import Mathlib.Analysis.Calculus.Deriv.Polynomial
import Mathlib.Analysis.Calculus.SmoothSeries
import Mathlib.Analysis.SpecialFunctions.ExpDeriv
import Mathlib.Analysis.Real.Pi.Bounds
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Tactic.Ring

set_option linter.style.header false

/-!
# The literal positive-side Riemann theta-series jet

The index `k : ℕ` represents the paper's strictly positive integer `n = k + 1`.
The polynomials are generated by the exact CERT12 recurrence.  In particular,
the functions below do not take the existence of a derivative jet as input.
-/

namespace PF4.Advancement.ThetaSeriesJet

open Filter Polynomial Set

/-- `P₀(X) = 2X - 3` and
`P_{j+1}(X) = (5/2 - 2X)P_j(X) + 2X P'_j(X)`. -/
noncomputable def certPoly : ℕ → ℝ[X]
  | 0 => C 2 * X - C 3
  | j + 1 => (C (5 / 2) - C 2 * X) * certPoly j +
      C 2 * X * (certPoly j).derivative

/-- The positive integer represented by the zero-based summation index. -/
def modeN (k : ℕ) : ℝ := (k + 1 : ℕ)

/-- The natural exponential coordinate `X = π n² e^{2t}`. -/
noncomputable def modeX (k : ℕ) (t : ℝ) : ℝ :=
  Real.pi * modeN k ^ 2 * Real.exp (2 * t)

/-- The `j`th recursive derivative mode of the theta summand. -/
noncomputable def thetaModeJet (j k : ℕ) (t : ℝ) : ℝ :=
  2 * Real.pi * modeN k ^ 2 * Real.exp ((5 / 2) * t) *
    (certPoly j).eval (modeX k t) * Real.exp (-(modeX k t))

/-- The literal summand in the positive-side Riemann theta-kernel formula. -/
noncomputable def thetaMode (k : ℕ) (t : ℝ) : ℝ :=
  (4 * Real.pi ^ 2 * modeN k ^ 4 * Real.exp ((9 / 2) * t) -
      6 * Real.pi * modeN k ^ 2 * Real.exp ((5 / 2) * t)) *
    Real.exp (-Real.pi * modeN k ^ 2 * Real.exp (2 * t))

theorem modeN_pos (k : ℕ) : 0 < modeN k := by
  unfold modeN
  exact_mod_cast Nat.succ_pos k

theorem modeX_pos (k : ℕ) (t : ℝ) : 0 < modeX k t := by
  unfold modeX
  exact mul_pos (mul_pos Real.pi_pos (sq_pos_of_pos (modeN_pos k))) (Real.exp_pos _)

theorem hasDerivAt_modeX (k : ℕ) (t : ℝ) :
    HasDerivAt (modeX k) (2 * modeX k t) t := by
  change HasDerivAt
    (fun s : ℝ => Real.pi * modeN k ^ 2 * Real.exp (2 * s))
    (2 * (Real.pi * modeN k ^ 2 * Real.exp (2 * t))) t
  have hinner : HasDerivAt (fun s : ℝ => 2 * s) 2 t := by
    simpa using (hasDerivAt_id t).const_mul (2 : ℝ)
  have h := ((Real.hasDerivAt_exp (2 * t)).comp t hinner).const_mul
    (Real.pi * modeN k ^ 2)
  simpa only [Function.comp_def, mul_assoc, mul_comm, mul_left_comm] using! h

theorem thetaModeJet_zero_eq_thetaMode (k : ℕ) (t : ℝ) :
    thetaModeJet 0 k t = thetaMode k t := by
  unfold thetaModeJet thetaMode certPoly modeX
  simp only [eval_sub, eval_mul, eval_C, eval_X]
  rw [show Real.exp ((9 / 2) * t) =
      Real.exp ((5 / 2) * t) * Real.exp (2 * t) by
    rw [← Real.exp_add]
    congr 1
    ring_nf]
  ring_nf

/-- Every recursive mode is the ordinary derivative of its predecessor. -/
theorem hasDerivAt_thetaModeJet (j k : ℕ) (t : ℝ) :
    HasDerivAt (thetaModeJet j k) (thetaModeJet (j + 1) k t) t := by
  let A : ℝ := 2 * Real.pi * modeN k ^ 2
  let x : ℝ := modeX k t
  let p : ℝ[X] := certPoly j
  have hx : HasDerivAt (modeX k) (2 * x) t := by
    simpa [x] using hasDerivAt_modeX k t
  have he : HasDerivAt (fun s : ℝ => Real.exp ((5 / 2) * s))
      ((5 / 2) * Real.exp ((5 / 2) * t)) t := by
    have hinner : HasDerivAt (fun s : ℝ => (5 / 2 : ℝ) * s) (5 / 2) t := by
      simpa using (hasDerivAt_id t).const_mul (5 / 2 : ℝ)
    simpa only [Function.comp_def, mul_comm] using!
      (Real.hasDerivAt_exp ((5 / 2) * t)).comp t hinner
  have hp : HasDerivAt (fun s : ℝ => p.eval (modeX k s))
      (p.derivative.eval x * (2 * x)) t := by
    simpa only [Function.comp_apply] using! (p.hasDerivAt x).comp t hx
  have hnegx : HasDerivAt (fun s : ℝ => -(modeX k s)) (-(2 * x)) t := hx.neg
  have hdecay : HasDerivAt (fun s : ℝ => Real.exp (-(modeX k s)))
      (-(2 * x) * Real.exp (-x)) t := by
    simpa only [Function.comp_def, mul_comm] using!
      (Real.hasDerivAt_exp (-x)).comp t hnegx
  have hraw := (((he.const_mul A).mul hp).mul hdecay)
  apply hraw.congr_of_eventuallyEq
      (Filter.Eventually.of_forall fun s => by simp [thetaModeJet, A, p]) |>.congr_deriv
  simp only [thetaModeJet, certPoly, eval_add, eval_mul, eval_sub, eval_C, eval_X]
  dsimp [A, x, p]
  ring_nf

/-- The literal theta function, stated only after the summands have been fixed. -/
noncomputable def thetaSeries (t : ℝ) : ℝ :=
  ∑' k : ℕ, thetaMode k t

/-- The candidate `j`th theta jet.  Its derivative status is proved below from
summability and locally uniform control, rather than built into this definition. -/
noncomputable def thetaSeriesJet (j : ℕ) (t : ℝ) : ℝ :=
  ∑' k : ℕ, thetaModeJet j k t

theorem thetaSeriesJet_zero_eq (t : ℝ) :
    thetaSeriesJet 0 t = thetaSeries t := by
  apply tsum_congr
  intro k
  exact thetaModeJet_zero_eq_thetaMode k t

/-- A shifted polynomial-times-exponential comparison series. -/
theorem summable_modeN_pow_mul_exp_neg (d : ℕ) {r : ℝ} (hr : 0 < r) :
    Summable fun k : ℕ => modeN k ^ d * Real.exp (-r * modeN k) := by
  have h := Real.summable_pow_mul_exp_neg_nat_mul d hr
  have hs := h.comp_injective Nat.succ_injective
  simpa [Function.comp_def, modeN, Nat.cast_succ] using hs

/-- At the central point the literal theta summand is controlled by an
explicit shifted exponential series. -/
theorem norm_thetaModeJet_zero_zero_le (k : ℕ) :
    ‖thetaModeJet 0 k 0‖ ≤
      (4 * Real.pi ^ 2 + 6 * Real.pi) * modeN k ^ 4 *
        Real.exp (-modeN k) := by
  let n := modeN k
  have hn : 1 ≤ n := by
    dsimp [n, modeN]
    exact_mod_cast Nat.succ_le_succ (Nat.zero_le k)
  have hn0 : 0 ≤ n := zero_le_one.trans hn
  have hn24 : n ^ 2 ≤ n ^ 4 := by nlinarith [sq_nonneg (n ^ 2 - n)]
  have hpi : 1 < Real.pi := lt_trans (by norm_num) Real.pi_gt_three
  have hexp : Real.exp (-Real.pi * n ^ 2) ≤ Real.exp (-n) := by
    apply Real.exp_monotone
    nlinarith [sq_nonneg n]
  have hcoef : 0 ≤ 4 * Real.pi ^ 2 + 6 * Real.pi := by positivity
  rw [thetaModeJet_zero_eq_thetaMode]
  simp only [thetaMode, mul_zero, Real.exp_zero, mul_one]
  change ‖(4 * Real.pi ^ 2 * n ^ 4 - 6 * Real.pi * n ^ 2) *
      Real.exp (-Real.pi * n ^ 2)‖ ≤
    (4 * Real.pi ^ 2 + 6 * Real.pi) * n ^ 4 * Real.exp (-n)
  rw [Real.norm_eq_abs]
  rw [abs_mul, abs_of_nonneg (Real.exp_nonneg _)]
  calc
    |4 * Real.pi ^ 2 * n ^ 4 - 6 * Real.pi * n ^ 2| *
          Real.exp (-Real.pi * n ^ 2) ≤
        (4 * Real.pi ^ 2 * n ^ 4 + 6 * Real.pi * n ^ 2) *
          Real.exp (-Real.pi * n ^ 2) := by
            apply mul_le_mul_of_nonneg_right _ (Real.exp_nonneg _)
            calc
              |4 * Real.pi ^ 2 * n ^ 4 - 6 * Real.pi * n ^ 2| ≤
                  |4 * Real.pi ^ 2 * n ^ 4| + |6 * Real.pi * n ^ 2| := abs_sub _ _
              _ = 4 * Real.pi ^ 2 * n ^ 4 + 6 * Real.pi * n ^ 2 := by
                rw [abs_of_nonneg (by positivity), abs_of_nonneg (by positivity)]
    _ ≤ (4 * Real.pi ^ 2 + 6 * Real.pi) * n ^ 4 *
          Real.exp (-Real.pi * n ^ 2) := by
            gcongr
            nlinarith [Real.pi_pos.le]
    _ ≤ (4 * Real.pi ^ 2 + 6 * Real.pi) * n ^ 4 * Real.exp (-n) := by
            exact mul_le_mul_of_nonneg_left hexp (mul_nonneg hcoef (by positivity))

theorem summable_thetaModeJet_zero_at_zero :
    Summable fun k : ℕ => thetaModeJet 0 k 0 := by
  apply ((summable_modeN_pow_mul_exp_neg 4 (r := 1) zero_lt_one).mul_left
    (4 * Real.pi ^ 2 + 6 * Real.pi)).of_norm_bounded
  intro k
  simpa only [neg_one_mul, mul_assoc] using norm_thetaModeJet_zero_zero_le k

/-- The exact analytic data still needed to pass six mode derivatives through
the infinite sum on an open connected set.  Crucially, this structure asks for
summable *bounds*, not for any derivative of the sum. -/
structure ThetaJetControl (s : Set ℝ) where
  isOpen : IsOpen s
  isPreconnected : IsPreconnected s
  zero_mem : (0 : ℝ) ∈ s
  majorant : ℕ → ℕ → ℝ
  majorantSummable : ∀ j, j < 6 → Summable (majorant j)
  derivativeBound : ∀ j, j < 6 → ∀ k t, t ∈ s →
    ‖thetaModeJet (j + 1) k t‖ ≤ majorant j k

namespace ThetaJetControl

/-- The concrete shape of the majorant produced on a bounded `t`-interval:
a fixed coefficient, a polynomial in `n`, and a decaying exponential. -/
noncomputable def exponentialMajorant (K : ℕ → ℝ) (r : ℝ)
    (j k : ℕ) : ℝ :=
  K j * modeN k ^ (2 * j + 6) * Real.exp (-r * modeN k)

theorem summable_exponentialMajorant (K : ℕ → ℝ) {r : ℝ} (hr : 0 < r)
    (j : ℕ) : Summable (exponentialMajorant K r j) := by
  change Summable fun k : ℕ =>
    K j * modeN k ^ (2 * j + 6) * Real.exp (-r * modeN k)
  simpa only [mul_assoc] using
    (summable_modeN_pow_mul_exp_neg (2 * j + 6) hr).mul_left (K j)

/-- Once the interval estimate has the explicit exponential shape, no further
convergence premise is needed: the comparison series is proved summable. -/
noncomputable def of_exponentialBound {s : Set ℝ}
    (hsOpen : IsOpen s) (hsConnected : IsPreconnected s) (hzero : (0 : ℝ) ∈ s)
    (K : ℕ → ℝ) {r : ℝ} (hr : 0 < r)
    (hbound : ∀ j, j < 6 → ∀ k t, t ∈ s →
      ‖thetaModeJet (j + 1) k t‖ ≤ exponentialMajorant K r j k) :
    ThetaJetControl s where
  isOpen := hsOpen
  isPreconnected := hsConnected
  zero_mem := hzero
  majorant := exponentialMajorant K r
  majorantSummable := fun j _ => summable_exponentialMajorant K hr j
  derivativeBound := hbound

/-- A control at derivative level `j - 1` also proves actual summability of
the level-`j` series.  Thus later uses of `tsum` are not vacuous defaults. -/
theorem summable_level {s : Set ℝ} (h : ThetaJetControl s) {j : ℕ}
    (hj : j ≤ 6) : Summable fun k : ℕ => thetaModeJet j k 0 := by
  cases j with
  | zero => exact summable_thetaModeJet_zero_at_zero
  | succ j =>
      have hjlt : j < 6 := Nat.lt_of_succ_le hj
      exact (h.majorantSummable j hjlt).of_norm_bounded fun k =>
        h.derivativeBound j hjlt k 0 h.zero_mem

/-- Termwise differentiation at every controlled level follows from the
literal mode recurrence and a locally uniform summable majorant. -/
theorem hasDerivAt_seriesJet {s : Set ℝ} (h : ThetaJetControl s)
    {j : ℕ} (hj : j < 6) {t : ℝ} (ht : t ∈ s) :
    HasDerivAt (thetaSeriesJet j) (thetaSeriesJet (j + 1) t) t := by
  have hsum := hasDerivAt_tsum_of_isPreconnected
    (h.majorantSummable j hj) h.isOpen h.isPreconnected
    (fun k y _ => hasDerivAt_thetaModeJet j k y)
    (h.derivativeBound j hj) h.zero_mem (h.summable_level hj.le) ht
  simpa only [thetaSeriesJet] using! hsum

/-- The complete ordinary derivative tower needed by the cleared raw-jet
certificate, restricted honestly to the controlled positive-side set. -/
theorem derivativeTowerThroughSix {s : Set ℝ} (h : ThetaJetControl s) :
    (∀ t ∈ s, HasDerivAt (thetaSeriesJet 0) (thetaSeriesJet 1 t) t) ∧
    (∀ t ∈ s, HasDerivAt (thetaSeriesJet 1) (thetaSeriesJet 2 t) t) ∧
    (∀ t ∈ s, HasDerivAt (thetaSeriesJet 2) (thetaSeriesJet 3 t) t) ∧
    (∀ t ∈ s, HasDerivAt (thetaSeriesJet 3) (thetaSeriesJet 4 t) t) ∧
    (∀ t ∈ s, HasDerivAt (thetaSeriesJet 4) (thetaSeriesJet 5 t) t) ∧
    (∀ t ∈ s, HasDerivAt (thetaSeriesJet 5) (thetaSeriesJet 6 t) t) := by
  constructor
  · intro t ht
    exact h.hasDerivAt_seriesJet (by omega) ht
  constructor
  · intro t ht
    exact h.hasDerivAt_seriesJet (by omega) ht
  constructor
  · intro t ht
    exact h.hasDerivAt_seriesJet (by omega) ht
  constructor
  · intro t ht
    exact h.hasDerivAt_seriesJet (by omega) ht
  constructor
  · intro t ht
    exact h.hasDerivAt_seriesJet (by omega) ht
  · intro t ht
    exact h.hasDerivAt_seriesJet (by omega) ht

end ThetaJetControl

end PF4.Advancement.ThetaSeriesJet
