"""sympy-generated division-free forms for C4, C4', C4'' in cumulants.

Generated by generate_c4_forms.py; do not edit by hand.
"""


def c4_jet(k2, k3, k4, k5, k6, k7, k8):
    """Return (C4, C4', C4'') from cumulants kappa_2..kappa_8."""
    x0 = k2*k4
    x1 = k3**4
    x2 = k4**3
    x3 = k3*k4
    x4 = 2*k5
    x5 = k5**2
    x6 = k2**3
    x7 = 2*x6
    x8 = k2**4
    x9 = 24*k4
    x10 = k3**2
    x11 = k6*x10
    x12 = 12*x10
    x13 = k2**2
    x14 = k3*x13
    x15 = k4**2
    x16 = k2*k5
    x17 = 24*x8
    x18 = 72*k2**5
    x19 = k3**3
    x20 = 38*k2
    x21 = 2*x13
    x22 = 48*x6
    x23 = 72*x13
    x24 = k3*k5
    c4 = 12*k2**6 - k2*x5 - 12*k5*x14 + k6*x0 + k6*x7 + x0*x12 - 9*x1 - 24*x10*x6 - x11 + 7*x13*x15 - x2 + x3*x4 + x8*x9
    c4_prime = k3*x15*x20 + k3*x18 + k3*x5 + k4*k5*x21 - k5*x15 + k5*x17 - 6*k6*x14 - k6*x16 + k6*x3 + k7*x0 - k7*x10 + k7*x7 - x12*x16 - x19*x23 - x19*x9 + x22*x3
    c4_second = -k2*k6**2 - 144*k2*x1 - 24*k2*x11 + k3*k6*x4 - 4*k4*k6*x13 - k4*x10*x23 + k4*x18 - k4*x5 - 36*k5*x19 + k6*x17 + k8*x0 - k8*x10 + k8*x7 + 56*x0*x24 - 34*x10*x15 + 360*x10*x8 + x15*x22 + x2*x20 + x21*x5 + 144*x24*x6
    return c4, c4_prime, c4_second


def c4_decomposition(k2, k3, k4, k5, k6):
    """Structural form: PF3 blocks + quadratic form - q-Hankel."""
    q, q1, q2, q3, q4 = -k2, -k3, -k4, -k5, -k6
    f_one = q * q2 - q1 * q1
    f_one_p = q * q3 - q1 * q2
    f_one_pp = q * q4 - q2 * q2
    hankel_q = (
        q * (q2 * q4 - q3 * q3)
        - q1 * (q1 * q4 - q2 * q3)
        + q2 * (q1 * q3 - q2 * q2)
    )
    cube = q * q * q
    return (
        3 * (2 * cube - f_one) * (2 * cube - 3 * f_one)
        + 2 * (q * q * f_one_pp - 6 * q * q1 * f_one_p + 9 * q1 * q1 * f_one)
        - hankel_q
    )
