#!/usr/bin/env python3
"""Generate division-free CSE forms for C4, C4', C4'' in cumulants.

C4 = det[m_{i+j-2}]_{4x4} is a weight-12 polynomial in kappa_2..kappa_6.
Since d/du kappa_j = kappa_{j+1}, the total u-derivatives are

    C4'  = sum_j dP/dk_j k_{j+1}              (needs kappa_7)
    C4'' = sum_{j,l} d2P/dk_j dk_l k_{j+1} k_{l+1} + sum_j dP/dk_j k_{j+2}
                                               (needs kappa_8)

The emitted module `c4_forms.py` evaluates all three with common-subexpression
elimination and no divisions, suitable for tight arb ball arithmetic. It also
emits the verified structural decomposition as an independent cross-check:

    C4 = 3(2q^3-F1)(2q^3-3F1) + 2(q^2 F1'' - 6 q q' F1' + 9 q'^2 F1) - det H3[q]

with q-derivatives q_i = -kappa_{i+2}.
"""

from __future__ import annotations

import sympy as sp

k = sp.symbols("k2:9")  # k[0]=kappa_2 ... k[6]=kappa_8
k2, k3, k4, k5, k6, k7, k8 = k

m2 = k2
m3 = k3
m4 = k4 + 3 * k2**2
m5 = k5 + 10 * k3 * k2
m6 = k6 + 15 * k4 * k2 + 10 * k3**2 + 15 * k2**3
P = sp.expand(
    m2 * (m2 * (2 * m3 * m5 + m4**2) - 3 * m3**2 * m4 - m5**2)
    + m3 * (m3**3 + 2 * m4 * m5)
    - m4**3
    + m6 * (m2 * (m4 - m2**2) - m3**2)
)

lower = [k2, k3, k4, k5, k6]
shift1 = {k2: k3, k3: k4, k4: k5, k5: k6, k6: k7}
shift2 = {k2: k4, k3: k5, k4: k6, k5: k7, k6: k8}

P1 = sp.expand(sum(sp.diff(P, kj) * shift1[kj] for kj in lower))
hess = sp.hessian(P, lower)
vec1 = sp.Matrix([shift1[kj] for kj in lower])
P2 = sp.expand((vec1.T * hess * vec1)[0, 0] + sum(sp.diff(P, kj) * shift2[kj] for kj in lower))

# Independent sanity: differentiate P along the shift flow twice symbolically.
t = sp.symbols("t")


def check_derivatives() -> None:
    # Model kappa_j(t) by generic jets and compare truncated Taylor data.
    a = sp.symbols("a2:11")  # jet coefficients kappa_j(0)=a_j, kappa_j'(0)=a_{j+1}...
    subs0 = {k[i]: a[i] for i in range(7)}
    kt = {lower[i]: a[i] + a[i + 1] * t + a[i + 2] * t**2 / 2 for i in range(5)}
    Pt = P.subs(kt)
    d1 = sp.diff(Pt, t).subs(t, 0)
    d2 = sp.diff(Pt, t, 2).subs(t, 0)
    assert sp.expand(d1 - P1.subs(subs0)) == 0, "P1 mismatch"
    assert sp.expand(d2 - P2.subs(subs0)) == 0, "P2 mismatch"
    print("symbolic derivative check: ok")


check_derivatives()

replacements, reduced = sp.cse([P, P1, P2], optimizations="basic")

lines = [
    '"""sympy-generated division-free forms for C4, C4\', C4\'\' in cumulants.',
    "",
    "Generated by generate_c4_forms.py; do not edit by hand.",
    '"""',
    "",
    "",
    "def c4_jet(k2, k3, k4, k5, k6, k7, k8):",
    '    """Return (C4, C4\', C4\'\') from cumulants kappa_2..kappa_8."""',
]
for symbol, expression in replacements:
    lines.append(f"    {symbol} = {sp.pycode(expression)}")
lines.append(f"    c4 = {sp.pycode(reduced[0])}")
lines.append(f"    c4_prime = {sp.pycode(reduced[1])}")
lines.append(f"    c4_second = {sp.pycode(reduced[2])}")
lines.append("    return c4, c4_prime, c4_second")
lines.append("")
lines.append("")
lines.append("def c4_decomposition(k2, k3, k4, k5, k6):")
lines.append('    """Structural form: PF3 blocks + quadratic form - q-Hankel."""')
lines.append("    q, q1, q2, q3, q4 = -k2, -k3, -k4, -k5, -k6")
lines.append("    f_one = q * q2 - q1 * q1")
lines.append("    f_one_p = q * q3 - q1 * q2")
lines.append("    f_one_pp = q * q4 - q2 * q2")
lines.append("    hankel_q = (")
lines.append("        q * (q2 * q4 - q3 * q3)")
lines.append("        - q1 * (q1 * q4 - q2 * q3)")
lines.append("        + q2 * (q1 * q3 - q2 * q2)")
lines.append("    )")
lines.append("    cube = q * q * q")
lines.append("    return (")
lines.append("        3 * (2 * cube - f_one) * (2 * cube - 3 * f_one)")
lines.append("        + 2 * (q * q * f_one_pp - 6 * q * q1 * f_one_p + 9 * q1 * q1 * f_one)")
lines.append("        - hankel_q")
lines.append("    )")
lines.append("")

with open("c4_forms.py", "w", encoding="utf-8") as handle:
    handle.write("\n".join(lines))
print("wrote c4_forms.py:", len(replacements), "shared subexpressions")
