/-
Copyright (c) 2026 ultimussaeculi. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: Joshuah Rainstar
-/

import PF4.Theta
import Mathlib.Analysis.Calculus.Deriv.Polynomial
import Mathlib.Analysis.Calculus.SmoothSeries
import Mathlib.Analysis.SpecialFunctions.ExpDeriv
import Mathlib.Analysis.Real.Pi.Bounds
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Tactic.Ring

set_option linter.style.header false

/-!
# The literal positive-mode Riemann-kernel jet

The index `k : ℕ` represents the paper's strictly positive integer `n = k + 1`.
The polynomials are generated by the exact CERT12 recurrence.  In particular,
the functions below do not take the existence of a derivative jet as input.
-/

namespace PF4

open Filter Polynomial Set

/-- `P₀(X) = 2X - 3` and
`P_{j+1}(X) = (5/2 - 2X)P_j(X) + 2X P'_j(X)`. -/
noncomputable def certPoly : ℕ → ℝ[X]
  | 0 => C 2 * X - C 3
  | j + 1 => (C (5 / 2) - C 2 * X) * certPoly j +
      C 2 * X * (certPoly j).derivative

/-- The natural exponential coordinate `X = π n² e^{2t}`. -/
noncomputable def modeX (k : ℕ) (t : ℝ) : ℝ :=
  Real.pi * modeN k ^ 2 * Real.exp (2 * t)

/-- The `j`th recursive derivative mode of the theta summand. -/
noncomputable def thetaModeJet (j k : ℕ) (t : ℝ) : ℝ :=
  2 * Real.pi * modeN k ^ 2 * Real.exp ((5 / 2) * t) *
    (certPoly j).eval (modeX k t) * Real.exp (-(modeX k t))

/-- The literal summand in the positive-side Riemann theta-kernel formula. -/
noncomputable def thetaMode (k : ℕ) (t : ℝ) : ℝ :=
  (4 * Real.pi ^ 2 * modeN k ^ 4 * Real.exp ((9 / 2) * t) -
      6 * Real.pi * modeN k ^ 2 * Real.exp ((5 / 2) * t)) *
    Real.exp (-Real.pi * modeN k ^ 2 * Real.exp (2 * t))

theorem modeX_pos (k : ℕ) (t : ℝ) : 0 < modeX k t := by
  unfold modeX
  exact mul_pos (mul_pos Real.pi_pos (sq_pos_of_pos (modeN_pos k))) (Real.exp_pos _)

theorem hasDerivAt_modeX (k : ℕ) (t : ℝ) :
    HasDerivAt (modeX k) (2 * modeX k t) t := by
  change HasDerivAt
    (fun s : ℝ => Real.pi * modeN k ^ 2 * Real.exp (2 * s))
    (2 * (Real.pi * modeN k ^ 2 * Real.exp (2 * t))) t
  have hinner : HasDerivAt (fun s : ℝ => 2 * s) 2 t := by
    simpa using (hasDerivAt_id t).const_mul (2 : ℝ)
  have h := ((Real.hasDerivAt_exp (2 * t)).comp t hinner).const_mul
    (Real.pi * modeN k ^ 2)
  simpa only [Function.comp_def, mul_assoc, mul_comm, mul_left_comm] using! h

theorem thetaModeJet_zero_eq_thetaMode (k : ℕ) (t : ℝ) :
    thetaModeJet 0 k t = thetaMode k t := by
  unfold thetaModeJet thetaMode certPoly modeX
  simp only [eval_sub, eval_mul, eval_C, eval_X]
  rw [show Real.exp ((9 / 2) * t) =
      Real.exp ((5 / 2) * t) * Real.exp (2 * t) by
    rw [← Real.exp_add]
    congr 1
    ring_nf]
  ring_nf

/-- Every recursive mode is the ordinary derivative of its predecessor. -/
theorem hasDerivAt_thetaModeJet (j k : ℕ) (t : ℝ) :
    HasDerivAt (thetaModeJet j k) (thetaModeJet (j + 1) k t) t := by
  let A : ℝ := 2 * Real.pi * modeN k ^ 2
  let x : ℝ := modeX k t
  let p : ℝ[X] := certPoly j
  have hx : HasDerivAt (modeX k) (2 * x) t := by
    simpa [x] using hasDerivAt_modeX k t
  have he : HasDerivAt (fun s : ℝ => Real.exp ((5 / 2) * s))
      ((5 / 2) * Real.exp ((5 / 2) * t)) t := by
    have hinner : HasDerivAt (fun s : ℝ => (5 / 2 : ℝ) * s) (5 / 2) t := by
      simpa using (hasDerivAt_id t).const_mul (5 / 2 : ℝ)
    simpa only [Function.comp_def, mul_comm] using!
      (Real.hasDerivAt_exp ((5 / 2) * t)).comp t hinner
  have hp : HasDerivAt (fun s : ℝ => p.eval (modeX k s))
      (p.derivative.eval x * (2 * x)) t := by
    simpa only [Function.comp_apply] using! (p.hasDerivAt x).comp t hx
  have hnegx : HasDerivAt (fun s : ℝ => -(modeX k s)) (-(2 * x)) t := hx.neg
  have hdecay : HasDerivAt (fun s : ℝ => Real.exp (-(modeX k s)))
      (-(2 * x) * Real.exp (-x)) t := by
    simpa only [Function.comp_def, mul_comm] using!
      (Real.hasDerivAt_exp (-x)).comp t hnegx
  have hraw := (((he.const_mul A).mul hp).mul hdecay)
  apply hraw.congr_of_eventuallyEq
      (Filter.Eventually.of_forall fun s => by simp [thetaModeJet, A, p]) |>.congr_deriv
  simp only [thetaModeJet, certPoly, eval_add, eval_mul, eval_sub, eval_C, eval_X]
  dsimp [A, x, p]
  ring_nf

/-- The literal theta function, stated only after the summands have been fixed. -/
noncomputable def thetaSeries (t : ℝ) : ℝ :=
  ∑' k : ℕ, thetaMode k t

/-- The candidate `j`th theta jet.  Its derivative status is proved below from
summability and locally uniform control, rather than built into this definition. -/
noncomputable def thetaSeriesJet (j : ℕ) (t : ℝ) : ℝ :=
  ∑' k : ℕ, thetaModeJet j k t

theorem thetaSeriesJet_zero_eq (t : ℝ) :
    thetaSeriesJet 0 t = thetaSeries t := by
  apply tsum_congr
  intro k
  exact thetaModeJet_zero_eq_thetaMode k t

/-- A shifted polynomial-times-exponential comparison series. -/
theorem summable_modeN_pow_mul_exp_neg (d : ℕ) {r : ℝ} (hr : 0 < r) :
    Summable fun k : ℕ => modeN k ^ d * Real.exp (-r * modeN k) := by
  have h := Real.summable_pow_mul_exp_neg_nat_mul d hr
  have hs := h.comp_injective Nat.succ_injective
  simpa [Function.comp_def, modeN, Nat.cast_succ] using hs

/-- At the central point the literal theta summand is controlled by an
explicit shifted exponential series. -/
theorem norm_thetaModeJet_zero_zero_le (k : ℕ) :
    ‖thetaModeJet 0 k 0‖ ≤
      (4 * Real.pi ^ 2 + 6 * Real.pi) * modeN k ^ 4 *
        Real.exp (-modeN k) := by
  let n := modeN k
  have hn : 1 ≤ n := by
    dsimp [n, modeN]
    exact_mod_cast Nat.succ_le_succ (Nat.zero_le k)
  have hn0 : 0 ≤ n := zero_le_one.trans hn
  have hn24 : n ^ 2 ≤ n ^ 4 := by nlinarith [sq_nonneg (n ^ 2 - n)]
  have hpi : 1 < Real.pi := lt_trans (by norm_num) Real.pi_gt_three
  have hexp : Real.exp (-Real.pi * n ^ 2) ≤ Real.exp (-n) := by
    apply Real.exp_monotone
    nlinarith [sq_nonneg n]
  have hcoef : 0 ≤ 4 * Real.pi ^ 2 + 6 * Real.pi := by positivity
  rw [thetaModeJet_zero_eq_thetaMode]
  simp only [thetaMode, mul_zero, Real.exp_zero, mul_one]
  change ‖(4 * Real.pi ^ 2 * n ^ 4 - 6 * Real.pi * n ^ 2) *
      Real.exp (-Real.pi * n ^ 2)‖ ≤
    (4 * Real.pi ^ 2 + 6 * Real.pi) * n ^ 4 * Real.exp (-n)
  rw [Real.norm_eq_abs]
  rw [abs_mul, abs_of_nonneg (Real.exp_nonneg _)]
  calc
    |4 * Real.pi ^ 2 * n ^ 4 - 6 * Real.pi * n ^ 2| *
          Real.exp (-Real.pi * n ^ 2) ≤
        (4 * Real.pi ^ 2 * n ^ 4 + 6 * Real.pi * n ^ 2) *
          Real.exp (-Real.pi * n ^ 2) := by
            apply mul_le_mul_of_nonneg_right _ (Real.exp_nonneg _)
            calc
              |4 * Real.pi ^ 2 * n ^ 4 - 6 * Real.pi * n ^ 2| ≤
                  |4 * Real.pi ^ 2 * n ^ 4| + |6 * Real.pi * n ^ 2| := abs_sub _ _
              _ = 4 * Real.pi ^ 2 * n ^ 4 + 6 * Real.pi * n ^ 2 := by
                rw [abs_of_nonneg (by positivity), abs_of_nonneg (by positivity)]
    _ ≤ (4 * Real.pi ^ 2 + 6 * Real.pi) * n ^ 4 *
          Real.exp (-Real.pi * n ^ 2) := by
            gcongr
            nlinarith [Real.pi_pos.le]
    _ ≤ (4 * Real.pi ^ 2 + 6 * Real.pi) * n ^ 4 * Real.exp (-n) := by
            exact mul_le_mul_of_nonneg_left hexp (mul_nonneg hcoef (by positivity))

theorem summable_thetaModeJet_zero_at_zero :
    Summable fun k : ℕ => thetaModeJet 0 k 0 := by
  apply ((summable_modeN_pow_mul_exp_neg 4 (r := 1) zero_lt_one).mul_left
    (4 * Real.pi ^ 2 + 6 * Real.pi)).of_norm_bounded
  intro k
  simpa only [neg_one_mul, mul_assoc] using norm_thetaModeJet_zero_zero_le k

/-- The exact analytic data still needed to pass six mode derivatives through
the infinite sum on an open connected set.  Crucially, this structure asks for
summable *bounds*, not for any derivative of the sum. -/
structure ThetaJetControl (s : Set ℝ) where
  isOpen : IsOpen s
  isPreconnected : IsPreconnected s
  zero_mem : (0 : ℝ) ∈ s
  majorant : ℕ → ℕ → ℝ
  majorantSummable : ∀ j, j < 6 → Summable (majorant j)
  derivativeBound : ∀ j, j < 6 → ∀ k t, t ∈ s →
    ‖thetaModeJet (j + 1) k t‖ ≤ majorant j k

namespace ThetaJetControl

/-- The concrete shape of the majorant produced on a bounded `t`-interval:
a fixed coefficient, a polynomial in `n`, and a decaying exponential. -/
noncomputable def exponentialMajorant (K : ℕ → ℝ) (r : ℝ)
    (j k : ℕ) : ℝ :=
  K j * modeN k ^ (2 * j + 6) * Real.exp (-r * modeN k)

theorem summable_exponentialMajorant (K : ℕ → ℝ) {r : ℝ} (hr : 0 < r)
    (j : ℕ) : Summable (exponentialMajorant K r j) := by
  change Summable fun k : ℕ =>
    K j * modeN k ^ (2 * j + 6) * Real.exp (-r * modeN k)
  simpa only [mul_assoc] using
    (summable_modeN_pow_mul_exp_neg (2 * j + 6) hr).mul_left (K j)

/-- Once the interval estimate has the explicit exponential shape, no further
convergence premise is needed: the comparison series is proved summable. -/
noncomputable def of_exponentialBound {s : Set ℝ}
    (hsOpen : IsOpen s) (hsConnected : IsPreconnected s) (hzero : (0 : ℝ) ∈ s)
    (K : ℕ → ℝ) {r : ℝ} (hr : 0 < r)
    (hbound : ∀ j, j < 6 → ∀ k t, t ∈ s →
      ‖thetaModeJet (j + 1) k t‖ ≤ exponentialMajorant K r j k) :
    ThetaJetControl s where
  isOpen := hsOpen
  isPreconnected := hsConnected
  zero_mem := hzero
  majorant := exponentialMajorant K r
  majorantSummable := fun j _ => summable_exponentialMajorant K hr j
  derivativeBound := hbound

/-- A control at derivative level `j - 1` also proves actual summability of
the level-`j` series.  Thus later uses of `tsum` are not vacuous defaults. -/
theorem summable_level {s : Set ℝ} (h : ThetaJetControl s) {j : ℕ}
    (hj : j ≤ 6) : Summable fun k : ℕ => thetaModeJet j k 0 := by
  cases j with
  | zero => exact summable_thetaModeJet_zero_at_zero
  | succ j =>
      have hjlt : j < 6 := Nat.lt_of_succ_le hj
      exact (h.majorantSummable j hjlt).of_norm_bounded fun k =>
        h.derivativeBound j hjlt k 0 h.zero_mem

/-- Termwise differentiation at every controlled level follows from the
literal mode recurrence and a locally uniform summable majorant. -/
theorem hasDerivAt_seriesJet {s : Set ℝ} (h : ThetaJetControl s)
    {j : ℕ} (hj : j < 6) {t : ℝ} (ht : t ∈ s) :
    HasDerivAt (thetaSeriesJet j) (thetaSeriesJet (j + 1) t) t := by
  have hsum := hasDerivAt_tsum_of_isPreconnected
    (h.majorantSummable j hj) h.isOpen h.isPreconnected
    (fun k y _ => hasDerivAt_thetaModeJet j k y)
    (h.derivativeBound j hj) h.zero_mem (h.summable_level hj.le) ht
  simpa only [thetaSeriesJet] using! hsum

/-- The complete ordinary derivative tower needed by the cleared raw-jet
certificate, restricted honestly to the controlled positive-side set. -/
theorem derivativeTowerThroughSix {s : Set ℝ} (h : ThetaJetControl s) :
    (∀ t ∈ s, HasDerivAt (thetaSeriesJet 0) (thetaSeriesJet 1 t) t) ∧
    (∀ t ∈ s, HasDerivAt (thetaSeriesJet 1) (thetaSeriesJet 2 t) t) ∧
    (∀ t ∈ s, HasDerivAt (thetaSeriesJet 2) (thetaSeriesJet 3 t) t) ∧
    (∀ t ∈ s, HasDerivAt (thetaSeriesJet 3) (thetaSeriesJet 4 t) t) ∧
    (∀ t ∈ s, HasDerivAt (thetaSeriesJet 4) (thetaSeriesJet 5 t) t) ∧
    (∀ t ∈ s, HasDerivAt (thetaSeriesJet 5) (thetaSeriesJet 6 t) t) := by
  constructor
  · intro t ht
    exact h.hasDerivAt_seriesJet (by omega) ht
  constructor
  · intro t ht
    exact h.hasDerivAt_seriesJet (by omega) ht
  constructor
  · intro t ht
    exact h.hasDerivAt_seriesJet (by omega) ht
  constructor
  · intro t ht
    exact h.hasDerivAt_seriesJet (by omega) ht
  constructor
  · intro t ht
    exact h.hasDerivAt_seriesJet (by omega) ht
  · intro t ht
    exact h.hasDerivAt_seriesJet (by omega) ht

end ThetaJetControl

/-!
## Concrete bounded-interval control

The quadratic exponential factor is weakened to an exponential in the positive summation
index.  This makes the comparison series polynomial-times-geometric and avoids
introducing any special-function integration or probability interface.
-/

namespace IntervalControl

/-- The finite coefficient `ℓ¹` norm used to bound a polynomial on the
nonnegative real axis. -/
noncomputable def coeffL1 (p : ℝ[X]) : ℝ :=
  ∑ i ∈ Finset.range (p.natDegree + 1), |p.coeff i|

theorem coeffL1_nonneg (p : ℝ[X]) : 0 ≤ coeffL1 p := by
  unfold coeffL1
  positivity

/-- A finite-support polynomial is bounded by its coefficient `ℓ¹` norm and
the largest monomial on `[0,∞)`. -/
theorem abs_eval_le_coeffL1_mul_max (p : ℝ[X]) {x : ℝ} (hx : 0 ≤ x) :
    |p.eval x| ≤ coeffL1 p * max 1 x ^ p.natDegree := by
  rw [p.eval_eq_sum_range]
  calc
    |∑ i ∈ Finset.range (p.natDegree + 1), p.coeff i * x ^ i| ≤
        ∑ i ∈ Finset.range (p.natDegree + 1), |p.coeff i * x ^ i| :=
      Finset.abs_sum_le_sum_abs _ _
    _ ≤ ∑ i ∈ Finset.range (p.natDegree + 1),
        |p.coeff i| * max 1 x ^ p.natDegree := by
      apply Finset.sum_le_sum
      intro i hi
      rw [abs_mul, abs_pow, abs_of_nonneg hx]
      apply mul_le_mul_of_nonneg_left _ (abs_nonneg _)
      exact (pow_le_pow_left₀ hx (le_max_right 1 x) i).trans
        (pow_le_pow_right₀ (le_max_left 1 x) (Nat.le_of_lt_succ (Finset.mem_range.mp hi)))
    _ = coeffL1 p * max 1 x ^ p.natDegree := by
      simp only [coeffL1, Finset.sum_mul]

/-- The interval coefficient controlling the natural exponential coordinate. -/
noncomputable def intervalC (B : ℝ) : ℝ :=
  max 1 (Real.pi * Real.exp (2 * B))

/-- The fixed exponential rate obtained from the lower endpoint `t > -1`. -/
noncomputable def intervalR : ℝ := Real.pi * Real.exp (-2)

/-- The closed coefficient for derivative level `j+1`. -/
noncomputable def intervalK (B : ℝ) (j : ℕ) : ℝ :=
  2 * Real.pi * Real.exp ((5 / 2) * B) * coeffL1 (certPoly (j + 1)) *
    intervalC B ^ (certPoly (j + 1)).natDegree

/-- The polynomial-times-geometric comparison sequence.  Its polynomial degree
is read from the finite recursive certificate polynomial itself, so no expanded
six-case derivative table is needed. -/
noncomputable def intervalMajorant (B : ℝ) (j k : ℕ) : ℝ :=
  intervalK B j *
    modeN k ^ (2 + 2 * (certPoly (j + 1)).natDegree) *
      Real.exp (-intervalR * modeN k)

theorem intervalR_pos : 0 < intervalR := by
  unfold intervalR
  positivity

theorem intervalC_one_le (B : ℝ) : 1 ≤ intervalC B := by
  exact le_max_left _ _

theorem intervalC_pos (B : ℝ) : 0 < intervalC B :=
  zero_lt_one.trans_le (intervalC_one_le B)

theorem intervalK_nonneg (B : ℝ) (j : ℕ) : 0 ≤ intervalK B j := by
  unfold intervalK
  exact mul_nonneg
    (mul_nonneg
      (mul_nonneg (by positivity) (Real.exp_nonneg _))
      (coeffL1_nonneg _))
    (pow_nonneg (intervalC_pos B).le _)

theorem summable_intervalMajorant (B : ℝ) (j : ℕ) :
    Summable (intervalMajorant B j) := by
  unfold intervalMajorant
  simpa only [mul_assoc] using
    (summable_modeN_pow_mul_exp_neg
      (2 + 2 * (certPoly (j + 1)).natDegree) intervalR_pos).mul_left (intervalK B j)

theorem modeN_le_sq (k : ℕ) : modeN k ≤ modeN k ^ 2 := by
  have hn := modeN_one_le k
  nlinarith [sq_nonneg (modeN k - 1)]

theorem modeX_le_interval (B : ℝ) (k : ℕ) {t : ℝ} (ht : t < B) :
    modeX k t ≤ intervalC B * modeN k ^ 2 := by
  have hexp : Real.exp (2 * t) ≤ Real.exp (2 * B) := by
    exact Real.exp_monotone (by linarith)
  have hpiExp : Real.pi * Real.exp (2 * t) ≤ Real.pi * Real.exp (2 * B) := by
    exact mul_le_mul_of_nonneg_left hexp Real.pi_pos.le
  have hC : Real.pi * Real.exp (2 * B) ≤ intervalC B := le_max_right _ _
  unfold modeX
  calc
    Real.pi * modeN k ^ 2 * Real.exp (2 * t) =
        (Real.pi * Real.exp (2 * t)) * modeN k ^ 2 := by ring
    _ ≤ intervalC B * modeN k ^ 2 := by
      exact mul_le_mul_of_nonneg_right (hpiExp.trans hC) (sq_nonneg _)

theorem one_le_interval_scale (B : ℝ) (k : ℕ) :
    1 ≤ intervalC B * modeN k ^ 2 := by
  have hC := intervalC_one_le B
  have hn := modeN_one_le k
  nlinarith [sq_nonneg (modeN k - 1)]

theorem max_modeX_le_interval (B : ℝ) (k : ℕ) {t : ℝ} (ht : t < B) :
    max 1 (modeX k t) ≤ intervalC B * modeN k ^ 2 := by
  exact max_le (one_le_interval_scale B k) (modeX_le_interval B k ht)

theorem exp_prefactor_le (B : ℝ) {t : ℝ} (ht : t < B) :
    Real.exp ((5 / 2) * t) ≤ Real.exp ((5 / 2) * B) := by
  apply Real.exp_monotone
  linarith

theorem exp_decay_le (k : ℕ) {t : ℝ} (ht : -1 < t) :
    Real.exp (-(modeX k t)) ≤ Real.exp (-intervalR * modeN k) := by
  apply Real.exp_monotone
  have hexp : Real.exp (-2) ≤ Real.exp (2 * t) := by
    exact Real.exp_monotone (by linarith)
  have hbase : intervalR * modeN k ^ 2 ≤ modeX k t := by
    unfold intervalR modeX
    calc
      Real.pi * Real.exp (-2) * modeN k ^ 2 =
          Real.pi * modeN k ^ 2 * Real.exp (-2) := by ring
      _ ≤ Real.pi * modeN k ^ 2 * Real.exp (2 * t) := by
        exact mul_le_mul_of_nonneg_left hexp (mul_nonneg Real.pi_pos.le (sq_nonneg _))
  have hlin : intervalR * modeN k ≤ intervalR * modeN k ^ 2 := by
    exact mul_le_mul_of_nonneg_left (modeN_le_sq k) intervalR_pos.le
  linarith

/-- The concrete locally uniform bound for every recursive derivative mode on
the bounded interval `(-1,B)`. -/
theorem norm_thetaModeJet_le_intervalMajorant (B : ℝ) (j k : ℕ) {t : ℝ}
    (ht : t ∈ Set.Ioo (-1 : ℝ) B) :
    ‖thetaModeJet (j + 1) k t‖ ≤ intervalMajorant B j k := by
  let p := certPoly (j + 1)
  let d := p.natDegree
  let n := modeN k
  let Cb := intervalC B
  have hn0 : 0 ≤ n := (modeN_pos k).le
  have hX0 : 0 ≤ modeX k t := (modeX_pos k t).le
  have hp := abs_eval_le_coeffL1_mul_max p hX0
  have hmax := max_modeX_le_interval B k ht.2
  have hpow : max 1 (modeX k t) ^ d ≤ (Cb * n ^ 2) ^ d := by
    exact pow_le_pow_left₀ (by positivity) (by simpa [Cb, n] using hmax) d
  have heval : |p.eval (modeX k t)| ≤ coeffL1 p * Cb ^ d * n ^ (2 * d) := by
    calc
      |p.eval (modeX k t)| ≤ coeffL1 p * max 1 (modeX k t) ^ d := hp
      _ ≤ coeffL1 p * (Cb * n ^ 2) ^ d := by
        exact mul_le_mul_of_nonneg_left hpow (coeffL1_nonneg p)
      _ = coeffL1 p * Cb ^ d * n ^ (2 * d) := by
        rw [mul_pow, ← pow_mul]
        ring
  have hpref := exp_prefactor_le B ht.2
  have hdecay := exp_decay_le k ht.1
  have hnonnegK : 0 ≤ 2 * Real.pi * n ^ 2 := by positivity
  unfold thetaModeJet intervalMajorant intervalK
  rw [Real.norm_eq_abs, abs_mul, abs_mul, abs_mul,
    abs_of_nonneg (by positivity : 0 ≤ 2 * Real.pi * modeN k ^ 2),
    abs_of_nonneg (Real.exp_nonneg _), abs_of_nonneg (Real.exp_nonneg _)]
  dsimp [p, d, n, Cb] at heval ⊢
  calc
    2 * Real.pi * modeN k ^ 2 * Real.exp ((5 / 2) * t) *
          |(certPoly (j + 1)).eval (modeX k t)| * Real.exp (-(modeX k t)) ≤
        2 * Real.pi * modeN k ^ 2 * Real.exp ((5 / 2) * B) *
          (coeffL1 (certPoly (j + 1)) * intervalC B ^ (certPoly (j + 1)).natDegree *
            modeN k ^ (2 * (certPoly (j + 1)).natDegree)) *
          Real.exp (-intervalR * modeN k) := by
      gcongr
      exact mul_nonneg
        (mul_nonneg (by positivity) (Real.exp_nonneg _))
        (mul_nonneg
          (mul_nonneg (coeffL1_nonneg _) (pow_nonneg (intervalC_pos B).le _))
          (pow_nonneg (modeN_pos k).le _))
    _ = (2 * Real.pi * Real.exp ((5 / 2) * B) * coeffL1 (certPoly (j + 1)) *
          intervalC B ^ (certPoly (j + 1)).natDegree) *
        modeN k ^ (2 + 2 * (certPoly (j + 1)).natDegree) *
          Real.exp (-intervalR * modeN k) := by
      rw [pow_add]
      ring

/-- A concrete `ThetaJetControl` on every bounded positive-side interval
containing zero. -/
noncomputable def onIoo (B : ℝ) (hB : 0 < B) :
    ThetaJetControl (Set.Ioo (-1 : ℝ) B) where
  isOpen := isOpen_Ioo
  isPreconnected := ordConnected_Ioo.isPreconnected
  zero_mem := by exact ⟨by norm_num, hB⟩
  majorant := intervalMajorant B
  majorantSummable := fun j _ => summable_intervalMajorant B j
  derivativeBound := fun j _ k t ht => norm_thetaModeJet_le_intervalMajorant B j k ht

/-- The literal theta series has its complete six-derivative ordinary jet on
every interval `(-1,B)` with `B>0`, with no remaining convergence premise. -/
theorem derivativeTowerThroughSix_on_Ioo (B : ℝ) (hB : 0 < B) :
    (∀ t ∈ Set.Ioo (-1 : ℝ) B,
      HasDerivAt (thetaSeriesJet 0) (thetaSeriesJet 1 t) t) ∧
    (∀ t ∈ Set.Ioo (-1 : ℝ) B,
      HasDerivAt (thetaSeriesJet 1) (thetaSeriesJet 2 t) t) ∧
    (∀ t ∈ Set.Ioo (-1 : ℝ) B,
      HasDerivAt (thetaSeriesJet 2) (thetaSeriesJet 3 t) t) ∧
    (∀ t ∈ Set.Ioo (-1 : ℝ) B,
      HasDerivAt (thetaSeriesJet 3) (thetaSeriesJet 4 t) t) ∧
    (∀ t ∈ Set.Ioo (-1 : ℝ) B,
      HasDerivAt (thetaSeriesJet 4) (thetaSeriesJet 5 t) t) ∧
    (∀ t ∈ Set.Ioo (-1 : ℝ) B,
      HasDerivAt (thetaSeriesJet 5) (thetaSeriesJet 6 t) t) :=
  (onIoo B hB).derivativeTowerThroughSix

/-- Pointwise positive-side form: every `t ≥ 0` lies in some controlled
bounded interval, so all six derivative identities hold there. -/
theorem derivativeTowerThroughSix_at_nonneg {t : ℝ} (ht : 0 ≤ t) :
    HasDerivAt (thetaSeriesJet 0) (thetaSeriesJet 1 t) t ∧
    HasDerivAt (thetaSeriesJet 1) (thetaSeriesJet 2 t) t ∧
    HasDerivAt (thetaSeriesJet 2) (thetaSeriesJet 3 t) t ∧
    HasDerivAt (thetaSeriesJet 3) (thetaSeriesJet 4 t) t ∧
    HasDerivAt (thetaSeriesJet 4) (thetaSeriesJet 5 t) t ∧
    HasDerivAt (thetaSeriesJet 5) (thetaSeriesJet 6 t) t := by
  let B := t + 1
  have hB : 0 < B := by dsimp [B]; linarith
  have htIoo : t ∈ Set.Ioo (-1 : ℝ) B := by
    dsimp [B]
    constructor <;> linarith
  rcases derivativeTowerThroughSix_on_Ioo B hB with
    ⟨h0, h1, h2, h3, h4, h5⟩
  exact ⟨h0 t htIoo, h1 t htIoo, h2 t htIoo, h3 t htIoo,
    h4 t htIoo, h5 t htIoo⟩

end IntervalControl

end PF4
